### ISSUE TITLE
Integration Epic

### ISSUE THREAD

**Issue by jr1221** [NEURoboticsClub/SpaceDroneEmbedded#4]
Integrate things together (will be edited frequently)

Depends on:
- [ ] #1 
- [x] #2 
- [ ] #3 
- [ ] #6 
- [ ] #7 

TODO:
- [ ] Have #2 and #3 send messages for state transition broadcast and fault code broadcast
- [ ] Have #2 recieve messages to change states
- [ ] Have #1 throw a fault on #3
- [ ] Add logging in all other files (#6)
- [ ] Have #2 send #7 commands and modes and whatnot, further develop control logic
